name: Test Bash Script

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Test bash script
      run: |
        sudo chmod +x ./Mount.sh
        sudo ./Mount.sh
